#!/usr/bin/env node

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  Tool,
} from '@modelcontextprotocol/sdk/types.js';
import { StellifyClient } from './stellify-client.js';
import dotenv from 'dotenv';
import { createRequire } from 'module';

// Load the Stellify Framework manifest (generated from stellify-framework package)
const require = createRequire(import.meta.url);
const frameworkManifest = require('stellify-framework/framework-api.json');

// Load environment variables
dotenv.config();

const API_URL = process.env.STELLIFY_API_URL || 'https://stellisoft.com/api/v1';
const API_TOKEN = process.env.STELLIFY_API_TOKEN;

if (!API_TOKEN) {
  console.error('Error: STELLIFY_API_TOKEN environment variable is required');
  process.exit(1);
}

// Initialize Stellify API client
const stellify = new StellifyClient({
  apiUrl: API_URL,
  apiToken: API_TOKEN,
});

// Define MCP tools
// Stellify Framework API - dynamically loaded from stellify-framework manifest
// The manifest is auto-generated by the stellify-framework build process

interface FrameworkManifest {
  version: string;
  generatedAt: string;
  composables: Record<string, {
    summary: string;
    options: Array<{ name: string; type: string; required: boolean; description?: string }>;
    returns: Array<{ name: string; type: string; description?: string }>;
  }>;
  utilities: Record<string, {
    summary: string;
    methods: Array<{ name: string; signature: string; description?: string }>;
    staticMethods?: Array<{ name: string; signature: string; description?: string }>;
  }>;
  rules: Array<{ name: string; signature: string; description?: string }>;
}

// Get the full framework API from the manifest
function getFrameworkAPI(moduleName?: string): any {
  const manifest = frameworkManifest as FrameworkManifest;

  if (moduleName) {
    // Check composables first (useX pattern)
    if (manifest.composables[moduleName]) {
      return { [moduleName]: manifest.composables[moduleName] };
    }
    // Check utilities
    if (manifest.utilities[moduleName]) {
      return { [moduleName]: manifest.utilities[moduleName] };
    }
    // Check rules
    if (moduleName === 'rules') {
      return { rules: manifest.rules };
    }

    // Not found
    const available = [
      ...Object.keys(manifest.composables),
      ...Object.keys(manifest.utilities),
      'rules'
    ].join(', ');
    return { error: `Module "${moduleName}" not found. Available: ${available}` };
  }

  // Return full API with manifest metadata
  return {
    version: manifest.version,
    generatedAt: manifest.generatedAt,
    composables: manifest.composables,
    utilities: manifest.utilities,
    rules: manifest.rules,
  };
}

const tools: Tool[] = [
  {
    name: 'get_stellify_framework_api',
    description: `Get Stellify Framework API reference with full type signatures. Import from "stellify-framework".

Returns composables (useForm, useAuth, etc.) with options/returns, utilities (Http, Collection, etc.) with methods/staticMethods, and validation rules.

Each item includes summary, type signatures, and JSDoc descriptions. Collection is iterable with v-for.`,
    inputSchema: {
      type: 'object',
      properties: {
        module: {
          type: 'string',
          description: 'Optional: specific module to get API for (e.g., "useForm", "Http", "rules"). Omit to get full API.',
        },
      },
    },
  },
  {
    name: 'get_project',
    description: `Get active project. Returns uuid, name, branches, and directories array.`,
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'create_file',
    description: `Create an empty file shell in a Stellify project. Returns file UUID.

For PHP: type='class', 'model', 'controller', or 'middleware'.
For Vue: type='js', extension='vue'. Auto-creates app.js and template route.

Pass 'includes' array for framework class dependencies (auto-resolved to UUIDs). Use 'models' array in save_file for project models.

**IMPORTANT - Check appJs response for Vue components:**
- If \`appJs.action_required === "create_or_select_mount_file"\`: No mount file exists. You MUST ask the user if they want to create a new app.js mount file before proceeding.
- If \`appJs.action_required === "register_component"\`: Mount file exists but component isn't registered. Call save_file on the mount file to add the component UUID to its includes array.`,
    inputSchema: {
      type: 'object',
      properties: {
        directory: {
          type: 'string',
          description: 'The UUID of the directory to create the file in (get from get_project directories array)',
        },
        name: {
          type: 'string',
          description: 'File name without extension (e.g., "Counter", "UserController")',
        },
        type: {
          type: 'string',
          enum: ['class', 'model', 'controller', 'middleware', 'js'],
          description: 'Type of file: "js" for JavaScript/Vue, others for PHP',
        },
        extension: {
          type: 'string',
          description: 'File extension. Use "vue" for Vue components, omit for PHP files.',
        },
        namespace: {
          type: 'string',
          description: 'PHP namespace (e.g., "App\\Services\\"). Only for PHP files.',
        },
        includes: {
          type: 'array',
          items: { type: 'string' },
          description: 'Array of namespace strings to include as dependencies (e.g., ["App\\Models\\User", "Illuminate\\Support\\Facades\\Hash"]). These are resolved to UUIDs automatically.',
        },
        module: {
          type: 'string',
          description: 'Optional module name to group this file with related code (e.g., "blog-posts", "user-auth"). Module is auto-created if it doesn\'t exist.',
        },
        attributes: {
          type: 'array',
          items: { type: 'string' },
          description: 'PHP 8 class-level attributes (e.g., ["Fillable([\'name\', \'email\'])"], ["ObservedBy(UserObserver::class)"]). Use search_attributes tool to find available attributes.',
        },
      },
      required: ['directory', 'name', 'type'],
    },
  },
  {
    name: 'create_method',
    description: `Create a method in a file. Pass 'body' to include implementation. Async auto-detected from \`await\`. For significant methods, include context fields.`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file to add the method to',
        },
        name: {
          type: 'string',
          description: 'Method name (e.g., "increment", "store", "handleClick")',
        },
        visibility: {
          type: 'string',
          enum: ['public', 'protected', 'private'],
          description: 'Method visibility (PHP only)',
        },
        is_static: {
          type: 'boolean',
          description: 'Static method (PHP only)',
        },
        is_async: {
          type: 'boolean',
          description: 'Async method (JS/Vue). Auto-detected if body contains await.',
        },
        returnType: {
          type: 'string',
          description: 'Return type (e.g., "int", "string", "void", "object")',
        },
        nullable: {
          type: 'boolean',
          description: 'Nullable return type (e.g., ?object)',
        },
        parameters: {
          type: 'array',
          description: 'Method parameters (created as clauses). Include datatype for TypeScript annotations.',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Parameter name' },
              datatype: { type: 'string', description: 'TypeScript type (e.g., "number", "string", "MouseEvent", "User"). Outputs as: (param: Type)' },
              type: { type: 'string', description: 'Clause type (default: variable)' },
              value: { type: 'string', description: 'Default value' },
            },
            required: ['name'],
          },
        },
        body: {
          type: 'string',
          description: 'Method body code. Auto-parses statements.',
        },
        summary: {
          type: 'string',
          description: 'Context: What this method does',
        },
        rationale: {
          type: 'string',
          description: 'Context: Why built this way',
        },
        references: {
          type: 'array',
          description: 'Context: Related entities [{uuid, type, relationship, note}]',
          items: { type: 'object' },
        },
        decisions: {
          type: 'array',
          description: 'Context: Design decisions',
          items: { type: 'string' },
        },
        attributes: {
          type: 'array',
          description: 'PHP 8 attributes for the method (e.g., ["Route(\\"/api/users\\")"], ["Middleware(\\"auth\\")"]). Use search_attributes tool to find available attributes.',
          items: { type: 'string' },
        },
      },
      required: ['file', 'name'],
    },
  },
  {
    name: 'add_method_body',
    description: `Append code to an existing method. Use this when you need to ADD MORE code to a method that already has statements.

**For new methods:** Use \`create_method\` with the \`body\` parameter instead - it creates the method with code in one call.

**Nested code is handled correctly.** The parser tracks brace/bracket/paren depth and only splits on semicolons at the top level. Arrow functions with block bodies, computed properties, and other nested constructs work as single statements.

Pass 'types' to specify TypeScript types for variables declared in the code.

IMPORTANT: This APPENDS to existing method statements. To REPLACE a method's code entirely:
1. Create a NEW method with create_method (with body parameter)
2. Update the file's 'data' array to include new method UUID (remove old one)
3. Update any element click handlers to reference the new method UUID
4. Delete the old method with delete_method`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file containing the method',
        },
        method: {
          type: 'string',
          description: 'UUID of the method to add code to',
        },
        code: {
          type: 'string',
          description: 'PHP code for the method body (just the statements, no function declaration). Example: "return $a + $b;"',
        },
        types: {
          type: 'object',
          description: 'Map of variable names to their base TypeScript types (e.g., { "result": "Todo" }). The assembler infers full types from code structure.',
          additionalProperties: { type: 'string' },
        },
      },
      required: ['file', 'method', 'code'],
    },
  },
  {
    name: 'save_method',
    description: `Update a method's properties. Use add_method_body to append code.

For significant changes, include context fields: summary, rationale, references, decisions.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the method to update',
        },
        name: {
          type: 'string',
          description: 'Method name',
        },
        visibility: {
          type: 'string',
          enum: ['public', 'protected', 'private'],
          description: 'Method visibility (PHP only)',
        },
        is_static: {
          type: 'boolean',
          description: 'Whether the method is static (PHP only)',
        },
        returnType: {
          type: 'string',
          description: 'Return type (e.g., "int", "string", "void", "object")',
        },
        nullable: {
          type: 'boolean',
          description: 'Whether the return type is nullable',
        },
        parameters: {
          type: 'array',
          description: 'Array of parameter clause UUIDs',
          items: { type: 'string' },
        },
        data: {
          type: 'array',
          description: 'Array of statement UUIDs that form the method body. Use to reorder or remove statements.',
          items: { type: 'string' },
        },
        is_async: {
          type: 'boolean',
          description: 'Whether the method is async (JavaScript/Vue only). Set to true for methods that use await.',
        },
        summary: {
          type: 'string',
          description: 'Context: Brief description of what this method does',
        },
        rationale: {
          type: 'string',
          description: 'Context: Why it was built this way',
        },
        references: {
          type: 'array',
          description: 'Context: Links to related entities [{uuid, type, relationship, note}]',
          items: {
            type: 'object',
            properties: {
              uuid: { type: 'string' },
              type: { type: 'string', enum: ['model', 'route', 'method', 'file', 'setting', 'element'] },
              relationship: { type: 'string', enum: ['uses', 'creates', 'updates', 'calls', 'contains', 'triggers'] },
              note: { type: 'string' },
            },
          },
        },
        decisions: {
          type: 'array',
          description: 'Context: Design decisions made',
          items: { type: 'string' },
        },
        attributes: {
          type: 'array',
          description: 'PHP 8 attributes for the method (e.g., ["Route(\\"/api/users\\")"], ["Middleware(\\"auth\\")"]). Use search_attributes tool to find available attributes.',
          items: { type: 'string' },
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'search_methods',
    description: 'Search for methods in the project by name or within a specific file',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Method name to search for (supports wildcards)',
        },
        file_uuid: {
          type: 'string',
          description: 'Optional: filter results to a specific file',
        },
      },
    },
  },
  {
    name: 'search_attributes',
    description: `Search for available PHP 8 attributes in Laravel. Returns attribute suggestions with descriptions, namespaces, targets (class/method/property/parameter), and expected arguments.

Use this before adding attributes to files or methods to find the correct attribute name and syntax.

**Three modes of operation:**

1. **List categories** (no params): Returns all available attribute categories
   - Call with no arguments to discover categories like "eloquent", "queue", "routing"

2. **List category attributes** (category only): Returns all attributes in a category
   - Example: category="eloquent" → returns Fillable, Hidden, ObservedBy, etc.

3. **Search by query** (query provided): Searches attribute names
   - Example: query="fill" → finds Fillable attribute
   - Can combine with category to search within a specific category`,
    inputSchema: {
      type: 'object',
      properties: {
        query: {
          type: 'string',
          description: 'Search term to match against attribute names (e.g., "fillable", "middleware", "tries"). Optional - omit to list categories or all attributes in a category.',
        },
        category: {
          type: 'string',
          description: 'Filter to a specific category (e.g., "eloquent", "queue", "routing", "console", "container", "request", "testing", "resource", "factory"). When provided without query, returns all attributes in that category.',
        },
        target: {
          type: 'string',
          enum: ['class', 'method', 'property', 'parameter'],
          description: 'Filter attributes by where they can be applied. Default: returns all.',
        },
      },
    },
  },
  {
    name: 'analyze_attributes',
    description: `Analyze PHP 8 attribute usage across a Stellify project. Useful for auditing, finding missing attributes, and searching attribute values.

**Three modes:**

1. **usage** (default): List all attributes used in the project with counts
   - Optional: file_type to filter (e.g., "model", "controller")
   - Returns: attribute names, counts, and files using each

2. **missing**: Find files of a specific type missing a required attribute
   - Required: file_type (e.g., "model", "class")
   - Required: attribute name (e.g., "Fillable", "FailOnUnknownFields")
   - Returns: files missing vs having the attribute

3. **search**: Find files where an attribute contains a specific value
   - Required: attribute name
   - Optional: value to search for in attribute args
   - Optional: file_type to filter
   - Returns: matching files with their attribute values

Example queries:
- "Find every FormRequest missing FailOnUnknownFields": mode=missing, file_type=class, attribute=FailOnUnknownFields
- "Find models where 'email' is fillable": mode=search, attribute=Fillable, value=email
- "List all attributes used": mode=usage`,
    inputSchema: {
      type: 'object',
      properties: {
        mode: {
          type: 'string',
          enum: ['usage', 'missing', 'search'],
          description: 'Analysis mode: "usage" (list all attributes), "missing" (find files missing an attribute), "search" (find files with specific attribute value). Default: usage.',
        },
        file_type: {
          type: 'string',
          description: 'Filter by file type (e.g., "model", "controller", "class", "middleware").',
        },
        attribute: {
          type: 'string',
          description: 'Attribute name to analyze (required for "missing" and "search" modes).',
        },
        value: {
          type: 'string',
          description: 'Value to search for in attribute arguments (for "search" mode).',
        },
      },
    },
  },
  {
    name: 'delete_method',
    description: 'Delete a method from a file by UUID. This permanently removes the method and all its code. Requires both the file UUID and method UUID.',
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file containing the method (required)',
        },
        uuid: {
          type: 'string',
          description: 'UUID of the method to delete',
        },
      },
      required: ['file', 'uuid'],
    },
  },
  {
    name: 'get_method',
    description: 'Get a method by UUID. Returns the method data including its parameters and body.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the method to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'search_files',
    description: 'Search for files in the project by name or type',
    inputSchema: {
      type: 'object',
      properties: {
        query: {
          type: 'string',
          description: 'File name pattern to search for',
        },
        type: {
          type: 'string',
          description: 'File type to filter by (class, model, controller, middleware)',
        },
      },
    },
  },
  {
    name: 'create_route',
    description: `Create a route/page. For API routes, you MUST pass BOTH controller AND controller_method UUIDs to wire execution.

IMPORTANT: Both 'controller' (file UUID) and 'controller_method' (method UUID) are required together for API routes to execute code. Without both, the route won't run any code.

Route params like {id} auto-inject into controller method parameters when names match.`,
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'string',
          description: 'The UUID of the Stellify project',
        },
        name: {
          type: 'string',
          description: 'Route/page name (e.g., "Home", "Counter", "notes.index")',
        },
        path: {
          type: 'string',
          description: 'URL path (e.g., "/", "/counter", "/api/notes")',
        },
        method: {
          type: 'string',
          enum: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
          description: 'HTTP method',
          default: 'GET',
        },
        type: {
          type: 'string',
          enum: ['web', 'api', 'channels', 'view'],
          description: 'Route type: "web" for pages, "api" for API endpoints, "channels" for WebSocket channels, "view" for Blade views',
          default: 'web',
        },
        controller: {
          type: 'string',
          description: 'UUID of the controller file. MUST be provided together with controller_method for API routes to execute code.',
        },
        controller_method: {
          type: 'string',
          description: 'UUID of the method to execute. MUST be provided together with controller for API routes to execute code.',
        },
        data: {
          type: 'object',
          description: 'Additional route data (title, description, element UUIDs)',
        },
        module: {
          type: 'string',
          description: 'Optional module name to group this route with related code (e.g., "blog-posts", "user-auth"). Module is auto-created if it doesn\'t exist.',
        },
        file: {
          type: 'string',
          description: 'UUID of the routes file (e.g., web.php) to register this route in. The route will be added to the file\'s data array.',
        },
      },
      required: ['project_id', 'name', 'path', 'method'],
    },
  },
  {
    name: 'get_route',
    description: `Get a route/page by UUID. Returns route details including name, path, and attached elements.

Use this to look up a route you created or to find existing routes in the project.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'The UUID of the route to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'save_route',
    description: `Update a route/page. Wire to controller with both controller and controller_method UUIDs. For significant routes, include context fields.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the route to update',
        },
        controller: {
          type: 'string',
          description: 'Controller file UUID. Requires controller_method.',
        },
        controller_method: {
          type: 'string',
          description: 'Method UUID. Requires controller.',
        },
        path: {
          type: 'string',
          description: 'URL path (e.g., "/api/notes")',
        },
        name: {
          type: 'string',
          description: 'Route name',
        },
        type: {
          type: 'string',
          enum: ['web', 'api', 'channels', 'view'],
        },
        method: {
          type: 'string',
          enum: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
        },
        middleware: {
          type: 'array',
          items: { type: 'string' },
        },
        public: {
          type: 'boolean',
          description: 'Public route (no auth)',
        },
        summary: {
          type: 'string',
          description: 'Context: What this endpoint does',
        },
        rationale: {
          type: 'string',
          description: 'Context: Why built this way',
        },
        references: {
          type: 'array',
          description: 'Context: Related entities [{uuid, type, relationship, note}]',
          items: { type: 'object' },
        },
        decisions: {
          type: 'array',
          description: 'Context: Design decisions',
          items: { type: 'string' },
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'delete_route',
    description: `Delete a route/page from the project by UUID. This permanently removes the route.

WARNING: This is destructive and cannot be undone. Any elements attached to this route will be deleted also.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the route to delete',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'search_routes',
    description: `Search for routes/pages in the project by name. Use this to find existing routes before creating new ones.

Returns paginated results with route details including UUID, name, path, and type.
Use the returned UUID with html_to_elements (page parameter) or get_route for full details.`,
    inputSchema: {
      type: 'object',
      properties: {
        search: {
          type: 'string',
          description: 'Search term to match route names (e.g., "Counter", "Home")',
        },
        type: {
          type: 'string',
          enum: ['web', 'api', 'channels', 'view'],
          description: 'Filter by route type: "web" for pages, "api" for endpoints, "channels" for WebSocket channels, "view" for Blade views',
        },
        per_page: {
          type: 'number',
          description: 'Results per page (default: 10)',
        },
      },
    },
  },
  {
    name: 'create_element',
    description: `Create a UI element. Provide page (route UUID) for root elements, or parent (element UUID) for children.

**s-slot elements (for layouts):**
Use type='s-slot' to create a slot placeholder in a layout. When a page uses the layout via \`<x-layout-name>\`, the page's children are injected where the s-slot is. Set 'name' property on the s-slot for named slots (default slot has name='default').`,
    inputSchema: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: [
            's-wrapper', 's-input', 's-form', 's-svg', 's-shape', 's-media',
            's-freestyle', 's-directive', 's-slot'
          ],
          description: 'Element type - must be one of the valid Stellify element types',
        },
        page: {
          type: 'string',
          description: 'UUID of the page/route to add the element to (for root elements)',
        },
        parent: {
          type: 'string',
          description: 'UUID of the parent element (for child elements)',
        },
      },
      required: ['type'],
    },
  },
  {
    name: 'update_element',
    description: `Update a UI element. Data object: tag, classes, text, event handlers (method UUIDs), classBindings. Set 'name' on root elements to create Blade views (e.g., name="notes.index" for view('notes.index')).

**For s-slot elements (layout placeholders):**
Set 'name' to define the slot name (e.g., name="header"). Default slot uses name="default".

**For elements targeting named slots:**
Set 'slot' property to specify which slot the element should be injected into (e.g., slot="header").

**For elements inside @foreach loops (SSR/Blade):**
Use these attributes to reference the loop variable (defaults to \`$item\`):
- \`textField\`: Field name for text content → outputs \`{{ $item->fieldName }}\`
- \`hrefField\`: Field name for href → outputs \`href="{{ $item->fieldName }}"\` (field value ONLY, no prefix)
- \`srcField\`: Field name for src → outputs \`src="{{ $item->fieldName }}"\`

**For hrefs with path prefixes (IMPORTANT):**
\`hrefField\` outputs ONLY the field value. There is NO \`hrefPrefix\` attribute.
For links like \`/post/slug-here\`, you MUST use \`hrefExpression\`:
- \`hrefExpression: "/post/{{ $item->slug }}"\` → outputs \`href="/post/{{ $item->slug }}"\`
- \`hrefExpression: "/category/{{ $item->slug }}"\` → outputs \`href="/category/{{ $item->slug }}"\`

**For complex Blade expressions in attributes:**
Use expression attributes when you need more than simple field access:
- \`hrefExpression\`: Blade expression for href → outputs \`href="..."\` with the expression
- \`srcExpression\`: Blade expression for src → outputs \`src="..."\` with the expression
- \`altExpression\`: Blade expression for alt → outputs \`alt="..."\` with the expression

Examples:
- Path prefix: \`hrefExpression: "/post/{{ $item->slug }}"\`
- Route helper: \`hrefExpression: "{{ route('posts.show', $item->slug) }}"\`

**For Blade text content:**
Use the \`statements\` array with statement UUIDs containing Blade code. The statement's \`code\` property will be output directly for Blade to evaluate.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the element to update',
        },
        data: {
          type: 'object',
          description: 'HTML attributes and Stellify fields (tag, classes, text, classBindings, click, submit). Context fields: summary, rationale, references, decisions.',
        },
      },
      required: ['uuid', 'data'],
    },
  },
  {
    name: 'get_element',
    description: 'Get a single element by UUID. Returns the element data with all its attributes.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the element to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'get_element_tree',
    description: 'Get an element with all its descendants (children, grandchildren, etc.) as a hierarchical tree structure.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the root element',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'delete_element',
    description: 'Delete an element and all its children (CASCADE). Returns the count of deleted elements.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the element to delete',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'search_elements',
    description: `Search for elements in the project. Useful for finding elements by name, type, or content.

Note: To reorder elements, use update_element to modify the parent element's 'data' array with the new order of child UUIDs.`,
    inputSchema: {
      type: 'object',
      properties: {
        search: {
          type: 'string',
          description: 'Search query to match against element name, type, or content',
        },
        type: {
          type: 'string',
          description: 'Filter by element type (e.g., s-wrapper, s-input)',
        },
        include_metadata: {
          type: 'boolean',
          description: 'Include additional metadata',
          default: false,
        },
        per_page: {
          type: 'number',
          description: 'Results per page (1-100)',
          default: 20,
        },
      },
    },
  },
  {
    name: 'html_to_elements',
    description: `Convert HTML to Stellify elements.

**IMPORTANT - Choose the right approach:**

**For SSR/Blade Pages (WordPress imports, static content, layouts):**
- MUST pass 'page' (route UUID) - elements attach to the route for server-side rendering
- This is the most common use case

**For Vue Components (client-side interactivity):**
- Omit 'page' - elements are standalone, referenced by file's template array
- Returns UUIDs to use in save_file's template array

**Where elements go:**
- Pass 'page' (route UUID): Elements attached to the route for SSR rendering
- Pass 'selection' (element UUID): Elements attached as children of existing element
- Omit both: Elements are standalone (Vue components only) - use returned UUIDs in save_file's template array

**⚠️ CRITICAL: Multiple Root Elements Limitation**
When HTML contains multiple root-level elements (e.g., <header>, <main>, <footer>), only the FIRST root element gets attached to the route. Other elements become orphaned!

**WRONG:** \`html_to_elements(page: routeUUID, elements: "<header>...</header><main>...</main><footer>...</footer>")\`
→ Only <header> attaches to route. <main> and <footer> are orphaned!

**CORRECT:** Make separate calls for each root element:
1. \`html_to_elements(page: routeUUID, elements: "<header>...</header>")\`
2. \`html_to_elements(page: routeUUID, elements: "<main>...</main>")\`
3. \`html_to_elements(page: routeUUID, elements: "<footer>...</footer>")\`

**OR** wrap all elements in a single container div.

**@click auto-wiring:** Pass 'file' UUID to auto-resolve @click="methodName" handlers. Methods must exist in the file first.

**Blade Syntax Handling:**
For SSR/Blade pages, do NOT pass raw Blade expressions in text or attributes. The HTML parser stores them literally which causes rendering issues. Instead:

1. **For static HTML:** Pass clean HTML without Blade syntax, then use \`update_element\` to add dynamic behavior
2. **For loop content:** After creating elements, use \`update_element\` with:
   - \`textField\`, \`hrefField\`, \`srcField\` for simple field access (outputs \`{{ $item->field }}\`)
   - \`hrefExpression\`, \`srcExpression\`, \`altExpression\` for paths with prefixes or complex expressions
   - \`statements\` array with statement UUIDs for text content with Blade code
3. **For conditionals:** Use \`s-directive\` elements as siblings (see update_element docs)

**IMPORTANT - Links with path prefixes:**
\`hrefField\` outputs ONLY the field value with no prefix. There is NO \`hrefPrefix\` attribute.
For links like \`/post/my-slug\`, use \`hrefExpression: "/post/{{ $item->slug }}"\` instead.

**Loop variable:** Inside \`@foreach\` loops created with \`s-directive\`, the default loop variable is \`$item\`. Use \`textField: "title"\` to output \`{{ $item->title }}\`.

Prefer SVG icons over emoji (encoding issues).`,
    inputSchema: {
      type: 'object',
      properties: {
        elements: {
          type: 'string',
          description: 'HTML string to convert',
        },
        page: {
          type: 'string',
          description: 'Route UUID to attach elements to. REQUIRED for SSR/Blade pages (WordPress imports, static content, layouts). Only omit for Vue component templates.',
        },
        selection: {
          type: 'string',
          description: 'Parent element UUID to attach to (alternative to page). Use when adding children to existing elements.',
        },
        file: {
          type: 'string',
          description: 'Vue component file UUID. Pass this to auto-wire @click handlers to method UUIDs.',
        },
        test: {
          type: 'boolean',
          description: 'If true, returns structure without creating elements',
        },
      },
      required: ['elements'],
    },
  },
  // =============================================================================
  // STATEMENT & FILE MANAGEMENT TOOLS
  // =============================================================================
  {
    name: 'get_statement',
    description: `Get a statement by UUID. Returns the statement data including its clauses (code tokens).`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'The UUID of the statement to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'create_statement',
    description: `Create empty statement (step 1 of 2). Call add_statement_code next. Prefer create_statement_with_code for single call.`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file to add the statement to',
        },
        method: {
          type: 'string',
          description: 'UUID of the method to add the statement to (for method body statements)',
        },
      },
    },
  },
  {
    name: 'create_statement_with_code',
    description: `Create a statement with code in one call. Preferred over two-step create_statement + add_statement_code.

Pass 'types' to specify TypeScript types for variables. The assembler infers the full type from code structure:
- \`ref([])\` + type "Todo" → outputs \`const todos: Ref<Todo[]>\`
- \`ref(0)\` + type "number" → outputs \`const count: Ref<number>\`
- \`reactive({})\` + type "State" → outputs \`const state: State\``,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file to add the statement to',
        },
        code: {
          type: 'string',
          description: 'The code for the statement (e.g., "const count = ref(0);")',
        },
        method: {
          type: 'string',
          description: 'UUID of the method to add the statement to (optional, for method body statements)',
        },
        types: {
          type: 'object',
          description: 'Map of variable names to their base TypeScript types (e.g., { "todos": "Todo", "count": "number" }). The assembler infers Ref<>, arrays, etc. from the code structure.',
          additionalProperties: { type: 'string' },
        },
      },
      required: ['file', 'code'],
    },
  },
  {
    name: 'add_statement_code',
    description: `Add code to an existing statement. This is step 2 of 2 - call this AFTER create_statement.

**ALTERNATIVE:** Use create_statement_with_code for a single-call approach that combines both steps.

The statement must already exist (created via create_statement). This parses and stores the code.

Examples:
- PHP: "use Illuminate\\Http\\Request;" or "private $items = [];"
- JS/Vue: "const count = ref(0);" or "import { ref } from 'vue';"`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file containing the statement',
        },
        statement: {
          type: 'string',
          description: 'UUID of the statement to add code to',
        },
        code: {
          type: 'string',
          description: 'The code to add (e.g., "const count = ref(0);")',
        },
      },
      required: ['file', 'statement', 'code'],
    },
  },
  {
    name: 'delete_statement',
    description: 'Delete a statement from a file by UUID. This permanently removes the statement (import, variable, ref, etc.).',
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file containing the statement',
        },
        method: {
          type: 'string',
          description: 'UUID of the method containing the statement (use "file" for file-level statements)',
        },
        uuid: {
          type: 'string',
          description: 'UUID of the statement to delete',
        },
      },
      required: ['file', 'method', 'uuid'],
    },
  },
  {
    name: 'save_statement',
    description: 'Update an existing statement. Use this to modify statement properties after creation.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the statement to update',
        },
        data: {
          type: 'object',
          description: 'Statement data to update',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'save_file',
    description: `Finalize a file. Full replacement - call get_file first to update existing files.

Required: uuid, name, type. For significant changes, include context fields: summary, rationale, references, decisions.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the file to save',
        },
        name: {
          type: 'string',
          description: 'File name (without extension)',
        },
        type: {
          type: 'string',
          enum: ['js', 'class', 'controller', 'model', 'middleware'],
          description: 'File type: "js" for JavaScript/Vue, others for PHP',
        },
        extension: {
          type: 'string',
          description: 'File extension: "vue" for Vue SFCs, "js" for JavaScript',
        },
        template: {
          type: 'array',
          items: { type: 'string' },
          description: 'Root element UUIDs for Vue <template>',
        },
        data: {
          type: 'array',
          items: { type: 'string' },
          description: 'Method UUIDs (from create_method)',
        },
        statements: {
          type: 'array',
          items: { type: 'string' },
          description: 'Statement UUIDs (imports, variables, refs)',
        },
        includes: {
          type: 'array',
          items: { type: 'string' },
          description: 'File UUIDs for local imports (e.g., Vue components imported by app.js) AND framework class UUIDs/namespaces. CRITICAL: For JS mount files, add imported Vue component UUIDs here or they won\'t be bundled. Use models array for project models.',
        },
        models: {
          type: 'array',
          items: { type: 'string' },
          description: 'Project model UUIDs (auto-namespaced). Do NOT duplicate in includes.',
        },
        frameworkImports: {
          type: 'array',
          items: { type: 'string' },
          description: 'Stellify framework modules to import (e.g., ["Http", "Form", "Collection"]). Auto-generates: import { Http, Form, Collection } from \'stellify-framework\';',
        },
        summary: {
          type: 'string',
          description: 'Context: What this file does and why it exists',
        },
        rationale: {
          type: 'string',
          description: 'Context: Why it was built this way',
        },
        references: {
          type: 'array',
          description: 'Context: Related entities [{uuid, type, relationship, note}]',
          items: { type: 'object' },
        },
        decisions: {
          type: 'array',
          description: 'Context: Design decisions',
          items: { type: 'string' },
        },
        attributes: {
          type: 'array',
          items: { type: 'string' },
          description: 'PHP 8 class-level attributes (e.g., ["Fillable([\'name\', \'email\'])"], ["ObservedBy(UserObserver::class)"]). Use search_attributes tool to find available attributes.',
        },
      },
      required: ['uuid', 'name', 'type'],
    },
  },
  {
    name: 'get_file',
    description: 'Get a file by UUID with all its metadata, methods, and statements.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the file to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'delete_file',
    description: `Delete a file from the project by UUID. This permanently removes the file and all its methods/statements.

WARNING: This is destructive and cannot be undone. Make sure the file is not referenced elsewhere before deleting.`,
    inputSchema: {
      type: 'object',
      properties: {
        directory: {
          type: 'string',
          description: 'UUID of the directory containing the file (get from get_project directories array or get_file response)',
        },
        uuid: {
          type: 'string',
          description: 'UUID of the file to delete',
        },
      },
      required: ['directory', 'uuid'],
    },
  },
  {
    name: 'get_directory',
    description: `Get a directory by UUID to see its contents.

Use this to inspect directories returned by get_project. The project's data array contains directory UUIDs.
Returns the directory name and list of files/subdirectories inside it.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'The UUID of the directory to retrieve',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'create_directory',
    description: `Create a new directory for organizing files.

Common directories:
- 'js' for JavaScript/Vue files
- 'css' for stylesheets
- 'components' for reusable components

IMPORTANT: Check existing directories first using get_project and get_directory before creating new ones.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Directory name (e.g., "js", "css", "components")',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'save_directory',
    description: 'Update an existing directory. Use this to rename or modify directory properties.',
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the directory to update',
        },
        name: {
          type: 'string',
          description: 'New directory name',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'broadcast_element_command',
    description: `Push real-time UI updates via WebSocket. Use for SHOW/DISPLAY/DEMONSTRATE requests.

Actions: update (modify element), create (ephemeral element), batch (multiple updates), delete.

Changes are EPHEMERAL (not saved). For persistent changes, use update_element or html_to_elements.`,
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['update', 'batch', 'delete', 'create'],
          description: 'The type of command to broadcast',
        },
        element: {
          type: 'string',
          description: 'UUID of the element to modify (required for update, delete, create)',
        },
        changes: {
          type: 'object',
          description: 'Object containing attribute changes (e.g., { classes: ["bg-blue-500"], text: "Hello" })',
        },
        updates: {
          type: 'array',
          description: 'Array of updates for batch action: [{ element: "uuid", changes: {...} }]',
          items: {
            type: 'object',
            properties: {
              element: { type: 'string' },
              changes: { type: 'object' },
            },
            required: ['element', 'changes'],
          },
        },
      },
      required: ['action'],
    },
  },
  {
    name: 'create_resources',
    description: `Scaffold Model, Controller, Service, and Migration. Routes are NOT auto-wired - use create_route after.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Resource name in PascalCase (e.g., "User", "BlogPost", "OrderItem")',
        },
        fields: {
          type: 'array',
          description: 'Array of field definitions for the model and migration',
          items: {
            type: 'object',
            properties: {
              name: {
                type: 'string',
                description: 'Field name in snake_case (e.g., "first_name", "is_active")',
              },
              type: {
                type: 'string',
                enum: ['string', 'integer', 'int', 'bigint', 'boolean', 'bool', 'float', 'double', 'decimal', 'date', 'datetime', 'timestamp', 'text', 'longtext', 'json', 'email'],
                description: 'Field data type',
              },
              nullable: {
                type: 'boolean',
                description: 'Allow NULL values (default: false)',
              },
              unique: {
                type: 'boolean',
                description: 'Add unique constraint (default: false)',
              },
              required: {
                type: 'boolean',
                description: 'Require in validation for store action (default: true)',
              },
              default: {
                description: 'Default value for the field',
              },
              max: {
                type: 'integer',
                description: 'Maximum length/value for validation',
              },
            },
            required: ['name'],
          },
        },
        relationships: {
          type: 'array',
          description: 'Array of relationship definitions',
          items: {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                enum: ['hasOne', 'hasMany', 'belongsTo', 'belongsToMany'],
                description: 'Relationship type',
              },
              model: {
                type: 'string',
                description: 'Related model name in PascalCase',
              },
              name: {
                type: 'string',
                description: 'Custom method name (defaults to camelCase of model)',
              },
            },
            required: ['type', 'model'],
          },
        },
        controller: {
          type: 'boolean',
          description: 'Create controller with CRUD actions (default: true)',
        },
        service: {
          type: 'boolean',
          description: 'Create service class for business logic (default: false)',
        },
        migration: {
          type: 'boolean',
          description: 'Create database migration (default: true)',
        },
        routes: {
          type: 'boolean',
          description: 'Create API routes (default: true)',
        },
        soft_deletes: {
          type: 'boolean',
          description: 'Add soft delete support to model and migration (default: false)',
        },
        api: {
          type: 'boolean',
          description: 'Generate API-style responses (default: true). Set to FALSE for SSR/Blade pages (controllers return views). Set to TRUE for API endpoints (controllers return JSON).',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'run_code',
    description: `Execute a method in sandboxed environment. Requires file and method UUIDs. Returns output, success, error, and optional benchmark data.`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the file containing the method to run (required)',
        },
        method: {
          type: 'string',
          description: 'UUID of the method to execute (required)',
        },
        args: {
          type: 'array',
          description: 'Arguments to pass to the method',
          items: {},
        },
        timeout: {
          type: 'number',
          description: 'Execution timeout in seconds (default: 30, max: 60)',
        },
        benchmark: {
          type: 'boolean',
          description: 'Enable benchmarking to measure execution time and memory usage',
        },
      },
      required: ['file', 'method'],
    },
  },
  {
    name: 'run_migration',
    description: `Apply a migration against the project's tenant database (creates/updates tables). Migrations need elevated Schema/DDL privileges that run_code forbids, so they have a dedicated runner. Pass the migration file UUID (returned by create_resources). Run this after create_resources to actually create the tables.`,
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'UUID of the migration file to apply (its up() method runs against the tenant DB)',
        },
      },
      required: ['file'],
    },
  },
  {
    name: 'publish',
    description: `Bundle a Vue component tree into an ESM loader served at /esm and attach its import-map to a page route, so the component renders in the browser without the editor. Pass the entry file UUID (the app.js mount file) and the route UUID of the page that hosts it. Run this after building a Vue component + its app.js mount and wiring a page route, to make the component actually render.`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the entry file (the app.js mount file that imports/mounts the component)',
        },
        route: {
          type: 'string',
          description: 'UUID of the page route that hosts the component (the import-map/loader is attached to it)',
        },
        filename: {
          type: 'string',
          description: 'Bundle filename slug (lowercase, digits, hyphens). Defaults to the entry file name.',
        },
        mode: {
          type: 'string',
          enum: ['bundle', 'esm'],
          description: 'Bundle mode (default: bundle). "esm" emits a vue3-sfc-loader loader with an esm.sh import-map.',
        },
      },
      required: ['uuid'],
    },
  },
  {
    name: 'request_capability',
    description: `Log a missing framework-level capability. Creates a ticket in the Stellify backlog.`,
    inputSchema: {
      type: 'object',
      properties: {
        capability: {
          type: 'string',
          description: 'Short name for the capability (e.g., "websocket-support", "s3-uploads", "social-oauth")',
        },
        description: {
          type: 'string',
          description: 'Detailed description of what capability is needed',
        },
        use_case: {
          type: 'string',
          description: 'The user requirement that triggered this request',
        },
        workaround: {
          type: 'string',
          description: 'Any temporary workaround, or "blocked" if none exists',
        },
        priority: {
          type: 'string',
          enum: ['low', 'medium', 'high', 'critical'],
          description: 'Suggested priority based on user need (default: medium)',
        },
      },
      required: ['capability', 'description', 'use_case'],
    },
  },
  {
    name: 'install_package',
    description: `Install a foundation package into the current project. Creates routes and other resources defined in the package manifest.

Returns success with installed counts, or error with code:
- PACKAGE_NOT_FOUND: Package name doesn't exist
- PACKAGE_NOT_INSTALLABLE: Package is disabled
- ALREADY_INSTALLED: Package routes already exist in project
- UNKNOWN_MANIFEST_KEY: Package requires newer platform version
- INSTALL_FAILED: Transaction failed`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Package name (e.g., "file-uploads")',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'list_capabilities',
    description: `List the capability catalog - libraries and services that can be enabled for the project (e.g. Sanctum, Livewire, Vue, Stripe).

Each capability includes:
- name, category, description
- type: "composer" (PHP) or "npm" (JavaScript) - determines whether it lands in composer.json or package.json
- packages: the actual dependencies added when enabled (e.g. { "laravel/sanctum": "^4.0" })
- config_keys: required configuration. If non-empty, the capability needs those settings (e.g. API keys via save_setting) BEFORE it can be enabled
- enabled: whether it is currently active for this project

Use this before set_capability to find the correct capability name and check its requirements.`,
    inputSchema: {
      type: 'object',
      properties: {
        category: {
          type: 'string',
          description: 'Optional: filter to a single category (e.g., "auth", "payments", "frontend").',
        },
        type: {
          type: 'string',
          enum: ['npm', 'composer'],
          description: 'Optional: filter by dependency type. "composer" for PHP packages, "npm" for JavaScript packages.',
        },
      },
    },
  },
  {
    name: 'set_capability',
    description: `Enable or disable a capability (library/service) for the current project.

Enabling adds the capability to the project so its packages are emitted into composer.json / package.json at build/export time (and may enable related framework features, e.g. Livewire directives).

IMPORTANT:
- Use list_capabilities first to get the exact capability name and check config_keys.
- Capabilities that require configuration (non-empty config_keys, e.g. Stripe/S3 secrets) CANNOT be enabled until those settings are saved (via save_setting). Attempting to enable one returns an error.
- This does not install code/routes - for foundation packages that scaffold routes, use install_package instead.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Capability name from list_capabilities (e.g., "sanctum", "livewire", "vue").',
        },
        enabled: {
          type: 'boolean',
          description: 'true to enable the capability for the project, false to disable it.',
        },
      },
      required: ['name', 'enabled'],
    },
  },
  {
    name: 'analyze_performance',
    description: `Analyze execution performance from logs. Types: full, slow_methods, high_query_methods, high_memory_methods, failure_rates, trend.`,
    inputSchema: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: ['full', 'slow_methods', 'high_query_methods', 'high_memory_methods', 'failure_rates', 'trend'],
          description: 'Type of analysis to run (default: full)',
        },
        days: {
          type: 'number',
          description: 'Number of days to analyze (default: 7)',
        },
        limit: {
          type: 'number',
          description: 'Maximum results for specific queries (default: 10)',
        },
      },
    },
  },
  {
    name: 'analyze_quality',
    description: `Analyze Laravel code for quality issues. Types: full, relationships, fillables, casts, routes. Returns actionable suggestions.`,
    inputSchema: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: ['full', 'relationships', 'fillables', 'casts', 'routes'],
          description: 'Type of analysis to run (default: full)',
        },
      },
    },
  },
  {
    name: 'get_setting',
    description: `Get a setting profile by name. Returns key-value pairs accessible via config() in code.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Setting profile name (e.g., "app", "database", "mail", or custom names like "vote")',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'save_setting',
    description: `Create or update a setting profile. Data is merged with existing values. Access via config('name.key') in code.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Setting profile name (e.g., "app", "vote", "features")',
        },
        data: {
          type: 'object',
          description: 'Key-value pairs for the setting (e.g., { "salt": "secret", "enabled": true })',
        },
      },
      required: ['name', 'data'],
    },
  },
  {
    name: 'delete_setting',
    description: `Delete a setting profile from the tenant's settings table.

WARNING: This permanently removes the entire setting profile and all its values.
This cannot be undone.

EXAMPLE:
{ "name": "vote" }

This removes the "vote" setting profile entirely.`,
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Setting profile name to delete',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'get_assembled_code',
    description: `Get the assembled source code for a file. Returns the actual Vue SFC or PHP class as it would be rendered.

Use this after save_file to verify the component was built correctly:
- Check that all methods are included
- Verify @click handlers are wired to methods
- Confirm imports and reactive state are present
- Spot any missing pieces before deployment`,
    inputSchema: {
      type: 'object',
      properties: {
        uuid: {
          type: 'string',
          description: 'UUID of the file to get assembled code for',
        },
      },
      required: ['uuid'],
    },
  },
];

// Server instructions for tool discovery (used by MCP Tool Search)
const SERVER_INSTRUCTIONS = `Stellify is a coding platform where code is stored as structured JSON in a database, enabling surgical AI edits. Build Laravel (PHP) applications with StellifyJS (a front-end Laravel extension framework that has adaptors for reactive frameworks such as Vue, React and library wrappers for chart.js etc.).

## Architecture

- Files are stored as json. The json has a data key that references its methods (using uuids), and each method has a data key that references statements, and each statement has a data key that references clauses.

## Choosing Between SSR Pages and Vue Components

**Use SSR/Blade Pages (routes + elements) when:**
- Building static pages, layouts, or content pages
- Importing from WordPress, HTML templates, or static sites
- No client-side interactivity needed beyond links/forms
- SEO is important

**Use Vue Components (files with type='js', extension='vue') when:**
- Client-side interactivity is required (counters, toggles, dynamic forms)
- Real-time updates needed
- Complex state management

**CRITICAL DIFFERENCE:**
- SSR Pages: Elements attach directly to routes. Use \`html_to_elements\` with \`page\` parameter (route UUID). Elements render via Blade.
- Vue Components: Elements are standalone, referenced by file's \`template\` array. Use \`html_to_elements\` WITHOUT \`page\` parameter.

## Workflow for SSR Pages (most common)
1. Research: Call get_project to understand current structure
2. Create route: \`create_route\` for each page
3. Add elements: \`html_to_elements\` with \`page\` parameter set to route UUID
4. Wire controller (if needed): \`save_route\` with controller and controller_method UUIDs

## Workflow for Vue Components (client-side interactivity)
1. Research: Call get_project to understand current structure
2. Create file: \`create_file\` with type='js', extension='vue'
3. Create methods: \`create_method\` (with body parameter)
4. Create state: \`create_statement_with_code\` for refs/reactive
5. Create template: \`html_to_elements\` WITHOUT \`page\` parameter (returns UUIDs)
6. **Handle mount file**: Check \`appJs\` in create_file response. If \`action_required\` exists, ask user about mount file
7. Finalize: \`save_file\` with template/data/statements arrays (include frameworkImports for composables)
8. Verify: Call \`get_assembled_code\` to check the output
`;

// Legacy detailed instructions preserved as comments for reference if needed

// Create MCP server
const server = new Server(
  {
    name: 'stellify-mcp',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
    },
    instructions: SERVER_INSTRUCTIONS,
  }
);

// Handle tool list requests
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return { tools };
});

// Handle tool execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  if (!args) {
    throw new Error('Arguments are required');
  }

  try {
    switch (name) {
      case 'get_stellify_framework_api': {
        const moduleName = args.module as string | undefined;
        const result = getFrameworkAPI(moduleName);

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      }

      case 'get_project': {
        const result = await stellify.getProject();
        const projectData = result.data || result;
        const projectMeta = projectData.project || {};
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Active project: "${projectMeta.name || 'unknown'}" (${projectMeta.uuid || 'unknown'})`,
                project: projectData,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_file': {
        const result = await stellify.createFile(args as any);
        const fileData = result.data || result;
        const appJs = fileData.appJs || result.appJs;

        let message = `Created file "${(args as any).name}" (UUID: ${fileData.uuid})`;
        if (appJs?.created) {
          message += `. Auto-created app.js (UUID: ${appJs.uuid}) with component registration.`;
        } else if (appJs?.updated) {
          message += `. Auto-updated app.js to include this component.`;
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message,
                file: fileData,
                appJs: appJs || null,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_method': {
        const result = await stellify.createMethod(args as any);
        const methodData = result.data || result;
        const hasBody = !!(args as any).body;

        const response: any = {
          success: true,
          message: hasBody
            ? `Created method "${(args as any).name}" with body (UUID: ${methodData.uuid})`
            : `Created method "${(args as any).name}" (UUID: ${methodData.uuid})`,
          method: methodData,
        };

        // Include statements and clauses if body was provided
        if (result.statements) {
          response.statements = result.statements;
        }
        if (result.clauses) {
          response.clauses = result.clauses;
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(response, null, 2),
            },
          ],
        };
      }

      case 'save_method': {
        const { uuid, ...data } = args as any;
        const result = await stellify.saveMethod(uuid, { uuid, ...data });
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Updated method "${uuid}"`,
                method: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'add_method_body': {
        const result = await stellify.addMethodBody(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: 'Method body parsed and saved successfully',
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'search_methods': {
        const result = await stellify.searchMethods(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                results: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'search_attributes': {
        const result = await stellify.searchAttributes(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                ...result,
              }, null, 2),
            },
          ],
        };
      }

      case 'analyze_attributes': {
        const result = await stellify.analyzeAttributes(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                ...result,
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_method': {
        const { file, uuid } = args as { file: string; uuid: string };
        const result = await stellify.deleteMethod(file, uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted method ${uuid} from file ${file}`,
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_method': {
        const { uuid } = args as { uuid: string };
        const result = await stellify.getMethod(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                method: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'search_files': {
        const result = await stellify.searchFiles(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                results: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_route': {
        const result = await stellify.createRoute(args as any);
        const routeData = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Created route "${(args as any).name}" at ${(args as any).path} (UUID: ${routeData.uuid}). Use this UUID for html_to_elements page parameter.`,
                route: routeData,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_route': {
        const result = await stellify.getRoute((args as any).uuid);
        const routeData = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Route: "${routeData.name}" at ${routeData.path}`,
                route: routeData,
              }, null, 2),
            },
          ],
        };
      }

      case 'save_route': {
        const { uuid, ...updateData } = args as any;
        const result = await stellify.saveRoute(uuid, updateData);
        const routeData = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Updated route "${uuid}"${updateData.controller ? ' with controller wiring' : ''}`,
                route: routeData,
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_route': {
        const { uuid } = args as { uuid: string };
        const result = await stellify.deleteRoute(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted route ${uuid}`,
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'search_routes': {
        const result = await stellify.searchRoutes(args as any);
        const routes = result.data || result;
        // Handle paginated response - data.data contains the actual routes array
        const routeData = routes.data || routes;
        const routeCount = Array.isArray(routeData) ? routeData.length : routes.total || 0;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Found ${routeCount} routes`,
                routes: routes,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_element': {
        const result = await stellify.createElement(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Created element of type "${(args as any).type}"`,
                element: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'update_element': {
        const { uuid, data } = args as any;
        const result = await stellify.updateElement(uuid, data);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Updated element ${uuid}`,
                element: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_element': {
        const { uuid } = args as any;
        const result = await stellify.getElement(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                element: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_element_tree': {
        const { uuid } = args as any;
        const result = await stellify.getElementTree(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Retrieved element tree for ${uuid}`,
                tree: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_element': {
        const { uuid } = args as any;
        const result = await stellify.deleteElement(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted element ${uuid} and ${result.deleted_count} total elements`,
                deleted_count: result.deleted_count,
              }, null, 2),
            },
          ],
        };
      }

      case 'search_elements': {
        const result = await stellify.searchElements(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Found ${result.data.length} elements`,
                elements: result.data,
                pagination: result.pagination,
              }, null, 2),
            },
          ],
        };
      }

      case 'html_to_elements': {
        const result = await stellify.htmlToElements(args as any);
        const elementCount = Object.keys(result.data || {}).length;
        const testMode = (args as any).test ? ' (TEST MODE - not created)' : '';
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Converted HTML to ${elementCount} elements${testMode}`,
                elements: result.data,
              }, null, 2),
            },
          ],
        };
      }

      // Statement & File Management handlers
      case 'get_statement': {
        const result = await stellify.getStatement((args as any).uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Statement retrieved`,
                statement: result.statement || result,
                clauses: result.clauses || null,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_statement': {
        const result = await stellify.createStatement(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Created statement (${result.data?.uuid || result.uuid})`,
                statement: result.data || result,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_statement_with_code': {
        const result = await stellify.createStatementWithCode(args as any);
        const statementData = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Created statement with code (UUID: ${statementData.uuid})`,
                statement: statementData.statement || statementData,
                statements: statementData.statements,
                clauses: statementData.clauses,
              }, null, 2),
            },
          ],
        };
      }

      case 'add_statement_code': {
        const result = await stellify.addStatementCode(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: 'Statement code added successfully',
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_statement': {
        const { file, method, uuid } = args as { file: string; method: string; uuid: string };
        const result = await stellify.deleteStatement(file, method, uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted statement ${uuid}`,
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'save_statement': {
        const { uuid, ...data } = args as any;
        const result = await stellify.saveStatement(uuid, { uuid, ...data });
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Saved statement ${uuid}`,
                statement: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'save_file': {
        const { uuid, ...data } = args as any;
        const result = await stellify.saveFile(uuid, { uuid, ...data });
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Saved file "${data.name || uuid}"`,
                file: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_file': {
        const { uuid } = args as any;
        const result = await stellify.getFile(uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                file: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_file': {
        const { directory, uuid } = args as { directory: string; uuid: string };
        const result = await stellify.deleteFile(directory, uuid);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted file ${uuid} from directory ${directory}`,
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_directory': {
        const result = await stellify.getDirectory((args as any).uuid);
        const dirData = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Directory: "${dirData.name}" (${dirData.uuid})`,
                directory: dirData,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_directory': {
        const result = await stellify.createDirectory(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: result.existing
                  ? `Using existing directory "${(args as any).name}" (${result.data?.uuid || result.uuid})`
                  : `Created directory "${(args as any).name}" (${result.data?.uuid || result.uuid})`,
                directory: result.data || result,
                existing: result.existing || false,
              }, null, 2),
            },
          ],
        };
      }

      case 'save_directory': {
        const { uuid, ...data } = args as any;
        const result = await stellify.saveDirectory(uuid, data);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Saved directory ${uuid}`,
                directory: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'broadcast_element_command': {
        const result = await stellify.broadcastElementCommand(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Broadcast ${(args as any).action} command${(args as any).element ? ` for element ${(args as any).element}` : ''}`,
                data: result,
              }, null, 2),
            },
          ],
        };
      }

      case 'create_resources': {
        const result = await stellify.createResources(args as any);
        const data = result.data || result;
        const stats = data.statistics || {};

        // Build summary of what was created
        const created = [];
        if (data.model) created.push(`Model (${data.model.uuid})`);
        if (data.controller) created.push(`Controller (${data.controller.uuid})`);
        if (data.service) created.push(`Service (${data.service.uuid})`);
        if (data.migration) created.push(`Migration (${data.migration.uuid})`);

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Created ${(args as any).name} resource: ${created.join(', ')} (${stats.files || 0} files, ${stats.methods || 0} methods)`,
                data: {
                  name: data.name,
                  model: data.model ? {
                    uuid: data.model.uuid,
                    name: data.model.name,
                    namespace: data.model.namespace,
                    methods: data.model.methods,
                  } : null,
                  controller: data.controller ? {
                    uuid: data.controller.uuid,
                    name: data.controller.name,
                    namespace: data.controller.namespace,
                    methods: data.controller.methods,
                  } : null,
                  service: data.service ? {
                    uuid: data.service.uuid,
                    name: data.service.name,
                    namespace: data.service.namespace,
                    methods: data.service.methods,
                  } : null,
                  migration: data.migration ? {
                    uuid: data.migration.uuid,
                    name: data.migration.name,
                    table: data.migration.table,
                  } : null,
                  statistics: stats,
                },
              }, null, 2),
            },
          ],
        };
      }

      case 'run_code': {
        const result = await stellify.runCode(args as any);
        const benchmarkInfo = (args as any).benchmark
          ? ` (${result.execution_time || 'N/A'}ms, ${result.memory_usage || 'N/A'})`
          : '';
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: result.success !== false,
                message: result.success !== false
                  ? `Code executed successfully${benchmarkInfo}`
                  : `Execution failed: ${result.error || 'Unknown error'}`,
                output: result.output,
                error: result.error,
                execution_time: result.execution_time,
                memory_usage: result.memory_usage,
              }, null, 2),
            },
          ],
        };
      }

      case 'run_migration': {
        const result = await stellify.runMigration((args as any).file);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: result.status === 200 || result.success !== false,
                message: result.message || 'Migration executed',
                data: result.data ?? result,
              }, null, 2),
            },
          ],
        };
      }

      case 'publish': {
        const result = await stellify.publish(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: result.success !== false,
                message: result.message || 'Bundle published',
                data: result.data ?? result,
              }, null, 2),
            },
          ],
        };
      }

      case 'request_capability': {
        const result = await stellify.requestCapability(args as any);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Capability request logged: "${(args as any).capability}"`,
                request_id: result.data?.uuid || result.uuid,
                data: result.data || result,
              }, null, 2),
            },
          ],
        };
      }

      case 'install_package': {
        const result = await stellify.installPackage((args as any).name);
        if (result.status === 'error') {
          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify(result, null, 2),
              },
            ],
          };
        }
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                status: 'success',
                message: `Package "${result.package}" v${result.version} installed successfully`,
                installed: result.installed,
              }, null, 2),
            },
          ],
        };
      }

      case 'list_capabilities': {
        const result = await stellify.listCapabilities(args as any);
        const data = result.data || result;
        const count = Array.isArray(data) ? data.length : (data.capabilities?.length ?? 0);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Found ${count} capabilities`,
                capabilities: data,
              }, null, 2),
            },
          ],
        };
      }

      case 'set_capability': {
        const { name: capName, enabled } = args as { name: string; enabled: boolean };
        const status = enabled ? 'available' : 'not_available';
        const result = await stellify.setCapability(capName, status);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Capability "${capName}" ${enabled ? 'enabled' : 'disabled'} for the project`,
                capability: result.data || result,
              }, null, 2),
            },
          ],
        };
      }

      case 'analyze_performance': {
        const result = await stellify.analyzePerformance(args as any);
        const data = result.data || result;
        const analysisType = (args as any).type || 'full';

        // Build message based on analysis type
        let message = '';
        if (analysisType === 'full') {
          message = data.summary || `Analyzed ${data.analyzed_executions || 0} executions`;
          if (data.issues?.length > 0) {
            message += ` - Found ${data.issues.length} potential issue(s)`;
          }
        } else if (analysisType === 'slow_methods') {
          const methods = data.slow_methods || data;
          message = `Found ${Array.isArray(methods) ? methods.length : 0} slow methods`;
        } else if (analysisType === 'high_query_methods') {
          const methods = data.high_query_methods || data;
          message = `Found ${Array.isArray(methods) ? methods.length : 0} methods with high query counts (potential N+1)`;
        } else if (analysisType === 'high_memory_methods') {
          const methods = data.high_memory_methods || data;
          message = `Found ${Array.isArray(methods) ? methods.length : 0} methods with high memory usage`;
        } else if (analysisType === 'failure_rates') {
          const methods = data.failure_rates || data;
          message = `Found ${Array.isArray(methods) ? methods.length : 0} methods with failures`;
        } else if (analysisType === 'trend') {
          const trend = data.trend || data;
          message = `Performance trend: ${Array.isArray(trend) ? trend.length : 0} days of data`;
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message,
                analysis_type: analysisType,
                data,
              }, null, 2),
            },
          ],
        };
      }

      case 'analyze_quality': {
        const result = await stellify.analyzeQuality(args as any);
        const data = result.data || result;
        const analysisType = (args as any).type || 'full';

        // Build message based on analysis type
        let message = '';
        const issues = data.issues || [];

        if (analysisType === 'full') {
          const summary = data.summary || {};
          message = `Analyzed ${summary.models_analyzed || 0} models, ${summary.controllers_analyzed || 0} controllers`;
          if (summary.total_issues > 0) {
            message += ` - Found ${summary.total_issues} issue(s): ${summary.high_severity || 0} high, ${summary.medium_severity || 0} medium, ${summary.low_severity || 0} low`;
          } else {
            message += ' - No issues found';
          }
        } else {
          message = `Found ${issues.length} ${analysisType} issue(s)`;
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message,
                analysis_type: analysisType,
                data,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_setting': {
        const result = await stellify.getSetting((args as any).name);
        const data = result.data || result;
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Retrieved setting "${(args as any).name}"`,
                setting: data,
              }, null, 2),
            },
          ],
        };
      }

      case 'save_setting': {
        const { name, data } = args as { name: string; data: Record<string, any> };
        await stellify.saveSetting(name, data);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Saved setting "${name}" with ${Object.keys(data).length} key(s)`,
                keys: Object.keys(data),
              }, null, 2),
            },
          ],
        };
      }

      case 'delete_setting': {
        await stellify.deleteSetting((args as any).name);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                success: true,
                message: `Deleted setting "${(args as any).name}"`,
              }, null, 2),
            },
          ],
        };
      }

      case 'get_assembled_code': {
        const result = await stellify.getAssembledCode(args.uuid as string);
        // Return just the code content for easy reading
        const code = result.files?.[0]?.content || result.data?.code || 'No code available';
        const fileName = result.files?.[0]?.path || result.entryPoint || 'unknown';
        return {
          content: [
            {
              type: 'text',
              text: `// ${fileName}\n\n${code}`,
            },
          ],
        };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error: any) {
    // Extract backend response data for better error messages
    const backendData = error.response?.data;
    const statusCode = error.response?.status;

    // Build a helpful error response
    const errorResponse: Record<string, any> = {
      success: false,
      error: backendData?.message || error.message || 'Request failed',
    };

    // Include hint if the backend provided one
    if (backendData?.hint) {
      errorResponse.hint = backendData.hint;
    }

    // Include validation errors if present
    if (backendData?.errors) {
      errorResponse.validation_errors = backendData.errors;
    }

    // Include status code for context
    if (statusCode) {
      errorResponse.status = statusCode;
    }

    // Include the original message if different from backend message
    if (backendData?.message && error.message && !error.message.includes(backendData.message)) {
      errorResponse.details = { message: backendData.message };
    }

    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify(errorResponse, null, 2),
        },
      ],
      isError: true,
    };
  }
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Stellify MCP server running on stdio');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
